name: Build and Package
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          CI: ""
        run: npm run build

      - name: Create tarball
        run: tar -C ./build -zcvf build.tar.gz .

      - name: Get Project Name
        id: project_name
        run: echo "::set-output name=name::$(echo ${{ github.repository }} | cut -d'/' -f2)"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN:  ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build.tar.gz
          asset_name: ${{ steps.project_name.outputs.name }}-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip